<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>


<%@ include file ="../common/jsp_sql_dbget.inc" %>

<tr>
<th>아이디</th>
<td><%=cust_id %></td>
</tr>


<tr>
<th>비밀번호</th>
<td><%=cust_pw %></td>
</tr>

<tr>
<th>이름</th>
<td><%=cust_name %></td>
</tr>

<tr>
<th>전화번호</th>
<td><%=cust_tel_no %></td>
</tr>

<tr>
<th>주소</th>
<td><%=cust_addr %></td>
</tr>

<tr>
<th>성별</th>
<td><%=cust_gender %></td>
</tr>

<tr>
<th>이메일</th>
<td><%=cust_email%></td>
</tr>


<tr>
<th>가입일자</th>
<td><%=cust_join_date%></td>
</tr>

